apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rate-limiter
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: m5zn.xlarge
    desiredCapacity: 3
    volumeSize: 80
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub
