apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rate-limiter
  labels:
    app: rate-limiter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rate-limiter
  template:
    metadata:
      labels:
        app: rate-limiter
    spec:
      containers:
      - image: muleax/rate-limiter:latest
        resources:
          requests:
            cpu: "3500m"
          limits:
            cpu: "4000m"
        imagePullPolicy: Always
        name: rate-limiter
        ports:
        - containerPort: 8080
          protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: app-server
  labels:
    app: app-server
spec:
  containers:
  - name: app-server
    image: muleax/app-server:latest
    resources:
      requests:
        cpu: "100m"
      limits:
        cpu: "500m"
    ports:
    - containerPort: 8000
      protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  containers:
  - name: redis
    image: redis:7.0.2
    resources:
      requests:
        cpu: "2000m"
      limits:
        cpu: "3500m"
    ports:
    - containerPort: 6379
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: app-server
spec:
  selector:
    app: app-server
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: rate-limiter
spec:
  type: LoadBalancer
  selector:
    app: rate-limiter
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
